// <auto-generated />
using DDAC_Flight_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DDAC_Flight_System.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    partial class FlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DDAC_Flight_System.Models.Customer", b =>
                {
                    b.Property<int>("customerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("name");

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("customerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DDAC_Flight_System.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("arrivalTime");

                    b.Property<DateTime>("departureTime");

                    b.Property<string>("destination");

                    b.Property<bool>("flightStatus");

                    b.Property<string>("origin");

                    b.Property<decimal>("price");

                    b.HasKey("ID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("DDAC_Flight_System.Models.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FlightIDID");

                    b.Property<string>("Status");

                    b.Property<decimal>("TotalPrice");

                    b.Property<int?>("TravelClassIDID");

                    b.Property<int?>("customerID");

                    b.HasKey("ID");

                    b.HasIndex("FlightIDID");

                    b.HasIndex("TravelClassIDID");

                    b.HasIndex("customerID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DDAC_Flight_System.Models.TravelClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassDescription");

                    b.Property<decimal>("ClassPrice");

                    b.HasKey("ID");

                    b.ToTable("TravelClasses");
                });

            modelBuilder.Entity("DDAC_Flight_System.Models.Reservation", b =>
                {
                    b.HasOne("DDAC_Flight_System.Models.Flight", "FlightID")
                        .WithMany()
                        .HasForeignKey("FlightIDID");

                    b.HasOne("DDAC_Flight_System.Models.TravelClass", "TravelClassID")
                        .WithMany()
                        .HasForeignKey("TravelClassIDID");

                    b.HasOne("DDAC_Flight_System.Models.Customer", "CustomerID")
                        .WithMany()
                        .HasForeignKey("customerID");
                });
#pragma warning restore 612, 618
        }
    }
}
